# Generated by Django 3.2.4 on 2021-06-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=122)),
                ('Name', models.CharField(max_length=122)),
                ('Password', models.CharField(max_length=16)),
                ('Mobileno', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
